# Generated by Django 4.0.3 on 2022-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Список дел')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Когда?')),
            ],
        ),
    ]
