# Generated by Django 4.0.3 on 2022-03-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_doing_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doing',
            name='date',
        ),
        migrations.AddField(
            model_name='doing',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
